---
- name: Prepare
  hosts: all
  become: false
  tasks:
    - name: Update package cache (Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - tar
          - gzip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat/CentOS)
      ansible.builtin.dnf:
        name:
          - wget
          - tar
          - gzip
        state: present
      when: ansible_os_family == "RedHat"
