---
- name: Converge
  hosts: all
  become: false
  vars:
    java_distribution: "oracle"
    java_version: "21"
    install_path: "/opt/java"
    set_java_home: true

  tasks:
    - name: "Include java_install role"
      ansible.builtin.include_role:
        name: "mubbyrex.java_installer"
